[profile.default]
src = 'contracts'
out = 'out'
test = 'test/foundry'
cache_path = 'cache/foundry'
verbosity = 3
# Solidity compiler
evm_version = 'paris'   # The EVM version by hardfork name. Using Paris to support chains running older EVM versions
solc_version = '0.8.27'
optimizer = true        # Enables or disables the optimizer
optimizer_runs = 200    # The number of optimizer runs
libs = [
    # We provide a set of useful contract utilities
    # in the lib directory of @layerzerolabs/toolbox-foundry:
    # 
    # - forge-std
    # - ds-test
    # - solidity-bytes-utils
    'node_modules/@layerzerolabs/toolbox-foundry/lib',
    'node_modules',
]

remappings = [
    # Due to a misconfiguration of solidity-bytes-utils, an outdated version
    # of forge-std is being dragged in
    # 
    # To remedy this, we'll remap the ds-test and forge-std imports to our own versions
    'ds-test/=node_modules/@layerzerolabs/toolbox-foundry/lib/ds-test',
    'forge-std/=node_modules/@layerzerolabs/toolbox-foundry/lib/forge-std',
    '@layerzerolabs/=node_modules/@layerzerolabs/',
    '@openzeppelin/=node_modules/@openzeppelin/',
]

[fuzz]
runs = 1000
